language: cpp
jobs:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    cache:
      apt: true
    addons:
      apt:
        sources:
        - sourceline: deb https://apt.kitware.com/ubuntu/ xenial main
          key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        - sourceline: deb https://apt.kitware.com/ubuntu/ xenial-rc main
        packages:
        - cmake
  - os: linux
    dist: xenial
    compiler: clang
    cache:
      apt: true
    addons:
      apt:
        sources:
        - sourceline: deb https://apt.kitware.com/ubuntu/ xenial main
          key_url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        - sourceline: deb https://apt.kitware.com/ubuntu/ xenial-rc main
        packages:
        - cmake
  - os: osx
    compiler: clang
    cache:
      directories:
      - "$HOME/Library/Caches/Homebrew"
      - "/usr/local/Homebrew"
before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi

env:
  global:
  - TRAVIS_CI=true
  - secure: jtUcNgyERksmbj5AxCFnK2CH3OZtSYMK65oTYgJB44P7nVz2DX2pi+cygeIjlUXJ9I2NOcCpHxXu0SlV+qdBZojnt5MMQC621w3AtEFtg/+LqTuE521fTeTUq4oovaBP1mNcVp2HnvDo8juOR3JUpAMVDJzmBm0hhtEzjS8dGUE=
  - GEMFURY_TOKEN=${GEMFURY_TOKEN}
  - secure: n4G8Um+f9Da6nf7yLLGuExwF+9XYZUyy3cfwx3dGo4HWbHOUmpVFXVcujiuEMlKj1DSjZKtkTUrwX24BuuUsHaKho0y4hIYFI4OAC5x154mCAu1R64KRt5WSBRsz7kZuHzol9R+ebxWg9fsFdc0D5P5Pe68YPtiMB9QMCbL9mPM=
  - GEMFURY_PASSWD=${GEMFURY_PASSWD}

before_install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/; export HOMEBREW_NO_AUTO_UPDATE=1; fi

install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libwxbase3.0 libwxgtk3.0-dev libwxsqlite3-3.0-dev libxml2-dev libcurl4-openssl-dev libssl-dev ninja-build expect; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gnu-sed wxmac cmake ninja openssl expect; fi

script:
  - echo $TRAVIS_OS_NAME
  - bash ${TRAVIS_BUILD_DIR}/ninja_build.sh
  - if [[ "$TRAVIS_BRANCH" == "releases/"* ]]; then bash ${TRAVIS_BUILD_DIR}/upload_gemfury.sh; fi

branches:
  only:
    - "/^issues.*$/"
    - "/^releases.*$/"
notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - echo $TRAVIS_OS_NAME
